# Time in seconds
# Current in amps
# position, velocity, and acceleration in device units

#Motor 1
front_left_drive_actuator:
  actuator_name: hexapodo/front_left_drive_actuator
  serial_number: '0x602060003001'

#Motor 2
front_right_drive_actuator:
  actuator_name: hexapodo/front_right_drive_actuator
  serial_number: '0x602060002998'

#Motor 3
middle_left_drive_actuator:
  actuator_name: hexapodo/middle_left_drive_actuator
  serial_number: '0x602060003005'

#Motor 4
middle_right_drive_actuator:
  actuator_name: hexapodo/middle_right_drive_actuator
  serial_number: '0x602060003002'

#Motor 5
back_left_drive_actuator:
  actuator_name: hexapodo/back_left_drive_actuator
  serial_number: '0x602060003010'

#Motor 6
back_right_drive_actuator:
  actuator_name: hexapodo/back_right_drive_actuator
  serial_number: '0x602060003013'
